name: test_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dropdown_button2: ^2.3.9
  flutter_secure_storage: ^8.0.0
  provider: ^6.1.2
  flutter_staggered_grid_view: ^0.7.0
  get_it: ^7.7.0
  signature: ^6.3.0
  uuid: ^4.4.0
  flutter_cache_manager: ^3.3.1
  collection: ^1.18.0
  image_picker: 
  shared_preferences: ^2.2.3
  flutter_native_splash: ^2.2.7
  overlay_support: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
  

flutter_native_splash:
  color: "#EEEEEE"
  android_12:
    image: assets/images/logo.png
  image: assets/images/logo.png
  color_dark: "#EEEEEE"
  image_dark: assets/images/logo.png
  android: true
  ios: true
flutter_icons:
  remove_alpha_ios: true
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo.png"